version: '2'

services:
  remo_watch:
    image: remo_watch:latest
    volumes:
      - "./config:/config:ro"
      # - "/share/Docker/Volumes/remo_watch/config:/config:ro"
    restart: always
    cpu_shares: 20
    mem_limit: "2048m"
    build:
      context: .
