version: '2'

services:
  app:
    image: bugfire/remo_watch:0.1.6
    volumes:
      - "./config:/config:ro"
    restart: always
    cpu_shares: 20
    mem_limit: "2048m"
    build:
      context: .
