version: '2'

services:
  app:
    image: bugfire/remo_watch:latest
    volumes:
      # - "/share/Docker/Volumes/remo_watch/config:/config:ro"
      - "./config:/config:ro"
    restart: always
    cpu_shares: 20
    mem_limit: "2048m"
    build:
      context: .
